### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by mbajur** [grassdog/middleman-webpack#1]
Hello

Have you any idea why this project might not work on linux? My issue is described more here: https://github.com/middleman/middleman/issues/2118

Basically - it works perfectly well on macOS but assets are not added to sitemap on linux OS

Thanks!

**Comment by grassdog** [comment]
I haven't tried it on Linux myself so not sure why. Looks like you might be running it in Docker too. That can add an extra level of complexity, especially when it comes to watching files mounted in Docker volumes. Sorry I can't be more helpful.

**Comment by vinc** [comment]
Same here, not working on Arch Linux, and I'm not using Docker.

The command `middleman server` generate the files in `.tmp/dist` but they are not served.

So as a workaround I'm doing this:

    $ middleman build
    $ cd build
    $ python -m http.server

Maybe we can leave this issue open while we figure out a way to make it run on GNU/Linux? Anyway, thanks for this repo, it's really useful!

**Comment by grassdog** [comment]
Cool. Happy to accept any PRs that get this running on Linux.

**Comment by evenreven** [comment]
[Someone in the Middleman issue thread suggested the clean-webpack-plugin is the culprit.](https://github.com/middleman/middleman/issues/2118#issuecomment-377577450)

But why would it work on MacOS if this is the case? Any ideas?
